
CREATE TABLE `categoria` (
  `ID_CATEGORIA` int NOT NULL,
  `NOM_CATEGORIA` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `detalle_pedido` (
  `ID_DETALLE_PEDIDO` int NOT NULL,
  `ID_PEDIDO` int DEFAULT NULL,
  `ID_PLATO` int DEFAULT NULL,
  `CANTIDAD` int DEFAULT NULL,
  `PRECIO` decimal(10,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



CREATE TABLE `mesa` (
  `ID_MESA` int NOT NULL,
  `NUMERO` int DEFAULT NULL,
  `CAPACIDAD` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pedido` (
  `ID_PEDIDO` int NOT NULL,
  `ID_MESA` int DEFAULT NULL,
  `ID_TRABAJADOR` int DEFAULT NULL,
  `F_PEDIDO` datetime DEFAULT NULL,
  `ESTADO` char(1) DEFAULT NULL,
  `TOTAL` decimal(10,2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `persona` (
  `ID_PERSONA` int NOT NULL,
  `NOMBRES` varchar(100) DEFAULT NULL,
  `APPATERNO` int DEFAULT NULL,
  `APMATERNO` int DEFAULT NULL,
  `DOCUMENTO` char(8) DEFAULT NULL,
  `CORREO` varchar(255) DEFAULT NULL,
  `TELEFONO` char(9) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `plato` (
  `ID_PLATO` int NOT NULL,
  `ID_CATEGORIA` int DEFAULT NULL,
  `NOMBRE` varchar(100) DEFAULT NULL,
  `DESCRIPCION` varchar(255) DEFAULT NULL,
  `PRECIO` decimal(10,2) DEFAULT NULL,
  `IMAGEN` longtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `privilegio` (
  `ID_PRIVILEGIO` int NOT NULL,
  `NOM_PRIVILEGIO` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `rol` (
  `ID_ROL` int NOT NULL,
  `NOM_ROL` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `trabajador` (
  `ID_TRABAJADOR` int NOT NULL,
  `ID_ROL` int DEFAULT NULL,
  `ID_PERSONA` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `usuario` (
  `ID_USUARIO` int NOT NULL,
  `ID_PERSONA` int DEFAULT NULL,
  `ID_PRIVILEGIO` int DEFAULT NULL,
  `PASSWORD` longtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


ALTER TABLE `categoria`
  ADD PRIMARY KEY (`ID_CATEGORIA`);

--
-- Indices de la tabla `detalle_pedido`
--
ALTER TABLE `detalle_pedido`
  ADD PRIMARY KEY (`ID_DETALLE_PEDIDO`),
  ADD KEY `DETALLEP_FK_PEDIDO` (`ID_PEDIDO`),
  ADD KEY `DETALLEP_FK_PLATO` (`ID_PLATO`);

--
-- Indices de la tabla `mesa`
--
ALTER TABLE `mesa`
  ADD PRIMARY KEY (`ID_MESA`);

--
-- Indices de la tabla `pedido`
--
ALTER TABLE `pedido`
  ADD PRIMARY KEY (`ID_PEDIDO`),
  ADD KEY `PEDIDO_FK_MESA` (`ID_MESA`),
  ADD KEY `PEDIDO_FK_TRABAJADOR` (`ID_TRABAJADOR`);

--
-- Indices de la tabla `persona`
--
ALTER TABLE `persona`
  ADD PRIMARY KEY (`ID_PERSONA`);

--
-- Indices de la tabla `plato`
--
ALTER TABLE `plato`
  ADD PRIMARY KEY (`ID_PLATO`),
  ADD KEY `PLATO_FK_CATEGORIA` (`ID_CATEGORIA`);

--
-- Indices de la tabla `privilegio`
--
ALTER TABLE `privilegio`
  ADD PRIMARY KEY (`ID_PRIVILEGIO`);

--
-- Indices de la tabla `rol`
--
ALTER TABLE `rol`
  ADD PRIMARY KEY (`ID_ROL`);

--
-- Indices de la tabla `trabajador`
--
ALTER TABLE `trabajador`
  ADD PRIMARY KEY (`ID_TRABAJADOR`),
  ADD KEY `TRABAJADOR_FK_ROL` (`ID_ROL`),
  ADD KEY `TRABAJADOR_FK_PERSONA` (`ID_PERSONA`);

--
-- Indices de la tabla `usuario`
--
ALTER TABLE `usuario`
  ADD PRIMARY KEY (`ID_USUARIO`),
  ADD KEY `USUARIO_FK_PERSONA` (`ID_PERSONA`),
  ADD KEY `USUARIO_FK_PRIVILEGIO` (`ID_PRIVILEGIO`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `categoria`
--
ALTER TABLE `categoria`
  MODIFY `ID_CATEGORIA` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `detalle_pedido`
--
ALTER TABLE `detalle_pedido`
  MODIFY `ID_DETALLE_PEDIDO` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `mesa`
--
ALTER TABLE `mesa`
  MODIFY `ID_MESA` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `pedido`
--
ALTER TABLE `pedido`
  MODIFY `ID_PEDIDO` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `persona`
--
ALTER TABLE `persona`
  MODIFY `ID_PERSONA` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `plato`
--
ALTER TABLE `plato`
  MODIFY `ID_PLATO` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `privilegio`
--
ALTER TABLE `privilegio`
  MODIFY `ID_PRIVILEGIO` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `rol`
--
ALTER TABLE `rol`
  MODIFY `ID_ROL` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `trabajador`
--
ALTER TABLE `trabajador`
  MODIFY `ID_TRABAJADOR` int NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT de la tabla `usuario`
--
ALTER TABLE `usuario`
  MODIFY `ID_USUARIO` int NOT NULL AUTO_INCREMENT;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `detalle_pedido`
--
ALTER TABLE `detalle_pedido`
  ADD CONSTRAINT `DETALLEP_FK_PEDIDO` FOREIGN KEY (`ID_PEDIDO`) REFERENCES `pedido` (`ID_PEDIDO`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `DETALLEP_FK_PLATO` FOREIGN KEY (`ID_PLATO`) REFERENCES `plato` (`ID_PLATO`) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Filtros para la tabla `pedido`
--
ALTER TABLE `pedido`
  ADD CONSTRAINT `PEDIDO_FK_MESA` FOREIGN KEY (`ID_MESA`) REFERENCES `mesa` (`ID_MESA`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `PEDIDO_FK_TRABAJADOR` FOREIGN KEY (`ID_TRABAJADOR`) REFERENCES `trabajador` (`ID_TRABAJADOR`) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Filtros para la tabla `plato`
--
ALTER TABLE `plato`
  ADD CONSTRAINT `PLATO_FK_CATEGORIA` FOREIGN KEY (`ID_CATEGORIA`) REFERENCES `categoria` (`ID_CATEGORIA`) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Filtros para la tabla `trabajador`
--
ALTER TABLE `trabajador`
  ADD CONSTRAINT `TRABAJADOR_FK_PERSONA` FOREIGN KEY (`ID_PERSONA`) REFERENCES `persona` (`ID_PERSONA`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `TRABAJADOR_FK_ROL` FOREIGN KEY (`ID_ROL`) REFERENCES `rol` (`ID_ROL`) ON DELETE RESTRICT ON UPDATE RESTRICT;

--
-- Filtros para la tabla `usuario`
--
ALTER TABLE `usuario`
  ADD CONSTRAINT `USUARIO_FK_PERSONA` FOREIGN KEY (`ID_PERSONA`) REFERENCES `persona` (`ID_PERSONA`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  ADD CONSTRAINT `USUARIO_FK_PRIVILEGIO` FOREIGN KEY (`ID_PRIVILEGIO`) REFERENCES `privilegio` (`ID_PRIVILEGIO`) ON DELETE RESTRICT ON UPDATE RESTRICT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
